## Database Settings
comet.db.host=127.0.0.1:3307
comet.db.username=comet_local
comet.db.password=comet_local_2026
comet.db.name=habbo

## Database Pool Settings
comet.db.pool.max=10
comet.db.pool.min=2
comet.db.pool.count=1
comet.db.pool.idleMaxAgeSeconds=30
comet.db.pool.maxConnectionAgeSeconds=60
comet.db.pool.acquireRetryAttempts=50
comet.db.pool.autoReconnect=true
comet.db.pool.tcpKeepAlive=true

## Network Settings
comet.network.host=127.0.0.1
comet.network.port=30000
comet.network.backlog=1500
comet.network.epoll=false
comet.network.acceptGroupThreads=2
comet.network.ioGroupThreads=2
comet.network.channelGroupThreads=4

comet.network.connectGroup=4
comet.network.bossGroup=4
comet.network.workerGroup=4
comet.network.messageHandlerThreads=4

comet.network.idleTimer.enabled=false
comet.network.idleTimer.readerIdleTime=60
comet.network.idleTimer.writerIdleTime=30
comet.network.idleTimer.allIdleTime=0
comet.network.maxPacketSize=500000

comet.network.alternativePacketHandling.enabled=false
comet.network.alternativePacketHandling.type=threadpool
comet.network.alternativePacketHandling.coreSize=8
comet.network.alternativePacketHandling.maxSize=32

## Game Settings
comet.game.rooms.data.max=5000
comet.game.rooms.data.lowerWatermark=0

## Logging Settings
comet.game.logging.enabled=true

## System Settings
## The amount of threads in the pool used by rooms and other stuff.
comet.system.catalogPurchaseThreads=2
comet.system.taskThreads=4
comet.system.taskRoomThreads=4
comet.system.roomLoaderThreads=4
comet.system.playerLoginThreads=16
comet.system.commandExecutorThreads=4
comet.system.BotThreads=4
comet.system.navigatorSearchThreads=16


comet.network.websocket.port=2096
comet.network.customWebSocket.port=30002

## Discord Webhooks
## name;endpointUrl|name;endpointUrl
comet.discord.username=RubyHotel
comet.discord.usernameLink=http://127.0.0.1
comet.discord.avatarUrl=http://127.0.0.1/assets/hotel-icon.png
comet.discord.webhooks=
